### ISSUE TITLE
Template

### ISSUE THREAD

**Issue by oneEyedSunday** [authguidance-examples/authguidance.websample2#3]
Hello @gary-archer did you use a template for the api code?

I like the structure and would like to use it for some projects.

**Comment by oneEyedSunday** [comment]
Also I cannot find the implementation of the token verification middleware mentioned in the article 
```js
const cognitoAuthMiddleware = cognitoAuth.getVerifyMiddleware()
app.use('/users', cognitoAuthMiddleware, usersRouter)
```

**Comment by gary-archer** [comment]
Hi,

I tend to define my own structure.
Eg it's often standard in Java / C# to separate host from logic, so I
follow the same pattern in Node.
Hope this helps,

Gary

**Comment by oneEyedSunday** [comment]
Structured seemed `enterprisey`. We are a node team, with some members having some php background. I did find the structure fascinating.
