### ISSUE TITLE
Question - OIDC implementation UI

### ISSUE THREAD

**Issue by vibingopal** [authguidance-examples/authguidance.websample2#8]
Thanks for the repo. Just want to check if the implementation of handling authentication is done by common component(Angular/React) by passing client id, secret and redirect URL on run time , is it better approach to implement the common component if many teams are using it. This way teams adopting it no need to add the same set of configuration files .

**Comment by gary-archer** [comment]
Hi - just saw this - apologies for the delay replying:

It is often a good idea with OAuth to factor out the plumbing code into reusable classes, as you say. My samples put this type of code into a plumbing folder. In a real company I would share classes, and in some cases use shared libraries, so that the application code remains business focused.

**Comment by vibingopal** [comment]
No Problem. Thank you for the response. One more question - I have seen if the Oauth provider is redirecting the user to the invalid page for any invalid client id/ Redirect URI . 
Now Instead of showing the oauth provider page, how can we redirect the user to the custom client page. I have tried with signinredirect (which is async function) using try and catch but OAuth provider page is getting displayed at the end instead of client-side page.

**Comment by gary-archer** [comment]
Until a valid client_id and redirect_uri are supplied, an Authorization Server (AS) will not return an OAuth error response to the caller. Instead it will sit in a rendered page. Once these 2 fields are supplied correctly the AS will return errors in an HTTP response in the `error / error_description` fields. This type of error will only happen in the early stages of integration, and not in production for real end users.

**Comment by vibingopal** [comment]
Sure. Thank you! We are seeing for the invalid client id and redirect URI, server-side page rendering is visible with details which we would like to overwrite with client-side page using try and catch in signinredirect but it seems like catch block is never getting executed for async function on usermanager. signinredirect. Need to check further.
